### ISSUE TITLE
Admin Dashboard System Capacity broken with German Locale

### ISSUE THREAD

**Issue by mdesaive** [apache/cloudstack#2539]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

With german locale settings, the graphics in the section "System Capacity" in the Dashboard are displayed incorrectly. 

##### STEPS TO REPRODUCE

~~~
echo LANG=\"de_DE.UTF-8\" > /etc/default/locale

service cloudstack-management restart

Login to CloudStack Web-UI
~~~

##### EXPECTED RESULTS

~~~
See the graphics for "System Capacity" displayed correctly.
~~~

##### ACTUAL RESULTS

~~~
The graphics show all red circles.
~~~

**Comment by DaanHoogland** [comment]
@mdesaive I am assuming that the line
echo "LANG="de_DE.UTF-8" > /etc/default/locale to
should read
echo LANG="de_DE.UTF-8" > /etc/default/locale

Did you test any other locales?
thanks

**Comment by rafaelweingartner** [comment]
Tested with en_AU, pt_BR, and de_DE (all UTF-8). for pt_BR and de_DE I got the same results (the issue reported here). For en_AU, everything worked just fine.

**Comment by mdesaive** [comment]
Yes. I reported correctly. The bug reproduces like described with the default installation.

My colleague patched the init script to set LANG/LC_ALL=C. ;)

Thanks for your effort!

**Comment by rhtyd** [comment]
I followed the step to set the locale to `de_DE.UTF-8`, restarted the mgmt server and before log in selected German as language. After login I see this (not sure if this has any error, maybe translation?):
![screenshot from 2018-05-09 16-25-41](https://user-images.githubusercontent.com/95203/39811271-c477ac8e-53a5-11e8-9b56-b240ebdbd3f5.png)

@mdesaive @rafaelweingartner @DaanHoogland what is the expected error/screenshot and any ideas on fixing it. I'll remove the milestone of 4.11.1.0 on this as I'm not sure how to approach a fix to the reported issue.

**Comment by s-seitz** [comment]
@rhtyd  answering on behalf of @mdesaive  , the error is not triggered by selecting another language inside the UI at the login prompt. Instead, it occurs if the system locale (LANG environment variable) is set to a region with comma as decimal "point". e.g. in germany float is noted as NN,NNN .

At least for debian/ubuntu prior systemd /etc/init.d/cloudstack-management contains

`if [ -r /etc/default/locale ]; then`
`        . /etc/default/locale`
`        export LANG`
`fi`

we simple fixed this via

`:~# cat /etc/default/locale `
`###LANG="de_DE.UTF-8"`
`## Cloudstack 4.11 Bug Decimalpoint versus Comma, we need a Point`
`LANG=C`
`LC_ALL=C`

**Comment by DaanHoogland** [comment]
I think more then just German locales will show this error, if the comma is the issue. We just haven't encountered them. I think this must be fixed with an in UI translation of the data coming in from the server.

**Comment by gentakojima** [comment]
This problem still persists. Affects too the Spanish locale (es_ES)

**Comment by rhtyd** [comment]
I'm not sure how to fix this one, any ideas @DaanHoogland @rafaelweingartner ? Should we export LANG via the /etc/default/cloudstack-management or open a docs PR?

**Comment by DaanHoogland** [comment]
@rhtyd we need to test that if we force LANG=C on the server we have no issues on the UI. If that's the case your solution should/could/would solve this.
Being Dutch, I never use Dutch, so I have no experience with this. (Dutch also uses a decimal comma instead of a point and uses the point for thousands separation to make things worse)
In general I prefer the reasonable default over the good documentation, if that answers your question.

**Comment by rhtyd** [comment]
Checked not reproducible @mdesaive can you test against Primate and re-open if you can reproduce against latest master or Primate. Thanks.
