### ISSUE TITLE
cloudstack-service-console-proxy-rdpclient - test fails

### ISSUE THREAD

**Issue by schadom** [apache/cloudstack#2682]
##### CLOUDSTACK VERSION
~~~
* Cloudstack 4.11.0.0-src
* Ubuntu 18.04 LTS
* JDK8
~~~

##### PROBLEM

	rob@cloudstack:~$ sudo apt update && sudo apt install mysql-connector-python python-software-properties debhelper openjdk-8-jdk libws-commons-util-java genisoimage libcommons-codec-java libcommons-httpclient-java liblog4j1.2-java maven
	rob@cloudstack:~$ wget http://www.apache.org/dyn/closer.lua/cloudstack/releases/4.11.0.0/apache-cloudstack-4.11.0.0-src.tar.bz2
	rob@cloudstack:~$ tar -jxvf apache-cloudstack-4.11.0.0-src.tar.bz2
	rob@cloudstack:~$ cd ./apache-cloudstack-4.11.0.0-src

	rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ mvn -p deps
	..
	..
	Tests run: 404, Failures: 0, Errors: 1, Skipped: 0
	..
	..
	[INFO] Apache CloudStack Plugin - Cloudian Connector ...... SUCCESS [  9.492 s]
	[INFO] Apache CloudStack Plugin - Prometheus Exporter ..... SUCCESS [  2.858 s]
	[INFO] Apache CloudStack Framework - Spring Module ........ SUCCESS [  5.730 s]
	[INFO] Apache CloudStack Secondary Storage Controller ..... SUCCESS [  5.386 s]
	[INFO] Apache CloudStack Client UI ........................ SUCCESS [ 17.402 s]
	[INFO] Apache CloudStack Console Proxy - RDP Client ....... FAILURE [  9.248 s]
	[INFO] Apache CloudStack Console Proxy .................... SKIPPED
	[INFO] Apache CloudStack Console Proxy - Server ........... SKIPPED
	[INFO] Apache CloudStack Framework - QuickCloud ........... SKIPPED
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 11:22 min
	[INFO] Finished at: 2018-05-29T21:08:07Z
	[INFO] Final Memory: 100M/745M
	[INFO] ------------------------------------------------------------------------
	[WARNING] The requested profile "deps" could not be activated because it does not exist.
	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project cloudstack-service-console-proxy-rdpclient: There are test failures.
	[ERROR]
	[ERROR] Please refer to /home/rob/apache-cloudstack-4.11.0.0-src/services/console-proxy-rdp/rdpconsole/target/surefire-reports for the individual test results.
	[ERROR] -> [Help 1]
	[ERROR]
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR]
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
	[ERROR]
	[ERROR] After correcting the problems, you can resume the build with the command
	[ERROR]   mvn <goals> -rf :cloudstack-service-console-proxy-rdpclient

	rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ cat ./services/console-proxy-rdp/rdpconsole/target/surefire-reports/rdpclient.MockServerTest.txt

	releases/4.11.0.0/-------------------------------------------------------------------------------
	Test set: rdpclient.MockServerTest
	-------------------------------------------------------------------------------
	Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.278 sec <<< FAILURE! - in rdpclient.MockServerTest
	testIsMockServerCanUpgradeConnectionToSsl(rdpclient.MockServerTest)  Time elapsed: 0.265 sec  <<< ERROR!
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	        at sun.security.ssl.Handshaker.activate(Handshaker.java:529)
	        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1492)
	        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	        at rdpclient.MockServerTest.testIsMockServerCanUpgradeConnectionToSsl(MockServerTest.java:166)

**Comment by schadom** [comment]
Fixed it by copying `jdk.tls.disabledAlgorithms=DH keySize < 128, RSA keySize < 128, DES keySize < 128, SHA1 keySize < 128, MD5 keySize < 128, RC4` from `./apache-cloudstack-4.11.0.0-src/client/conf/java.security.ciphers.in` to `/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security`.

**Comment by DaanHoogland** [comment]
thanks @schadom . Don't you feel this is a documentation bug of some sort?

**Comment by Xsenonn** [comment]
I couldn't find any other solution so if you don't mind I'll reopen thread here. I did as @schadom suggested but I'm still getting error below. 
The problem lies in Apache CloudStack Console Proxy - RDP Client but I don't know how to fix it. I'm trying to build version 4.12.0.0.
![Cloudstack-Error](https://user-images.githubusercontent.com/17640891/60894225-cf91cb80-a251-11e9-88d0-5a53c4329b6a.png)

**Comment by ustcweizhou** [comment]
@Xsenonn you can skip tests by adding "-DskipTests" to your mvn command
