### ISSUE TITLE
VM snapshot revert failure without memory

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3196]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Snapshot,xenserver
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
4.11.2
~~~

##### OS / ENVIRONMENT

XenServer 7.1.2 (XenServer 7.1CU2)

##### SUMMARY

VM snapshot revert failure without memory

2019-01-23 00:06:54,226 DEBUG [c.c.v.s.VMSnapshotManagerImpl] (Work-Job-Executor-156:ctx-28f7465a job-2867/job-2869 ctx-a04e0ed9) (logid:a9ef7fe7) Failed to revert vmsnapshot: 27
com.cloud.utils.exception.CloudRuntimeException: Revert VM: i-2-33-VM to snapshot: i-2-33-VM_VS_20190122155503 failed due to  Hypervisor com.cloud.hypervisor.xenserver.resource.XenServer650Resource doesn't support guest OS type CentOS 7. you can choose 'Other install media' to run it as HVM
      at org.apache.cloudstack.storage.vmsnapshot.DefaultVMSnapshotStrategy.revertVMSnapshot(DefaultVMSnapshotStrategy.java:393)
      at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateRevertToVMSnapshot(VMSnapshotManagerImpl.java:846)
      at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateRevertToVMSnapshot(VMSnapshotManagerImpl.java:1211)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
      at com.cloud.vm.snapshot.VMSnapshotManagerImpl.handleVmWorkJob(VMSnapshotManagerImpl.java:1224)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
      at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
      at com.sun.proxy.$Proxy198.handleVmWorkJob(Unknown Source)
      at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
      at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:581)
      at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
      at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
      at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
      at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:529)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)

##### STEPS TO REPRODUCE

~~~
Start instance
task vm snapshot (Do not select Snapshot memory)
Stop VM
Revert to VM snapshot
~~~

##### EXPECTED RESULTS

~~~
Revert success
~~~

##### ACTUAL RESULTS

~~~
Revert failure
~~~

**Comment by DaanHoogland** [comment]
@div8cn there seems to be no related activity. Is someone looking into this? I will move it out of this milestone if there is no interest to solve this.

**Comment by div8cn** [comment]
This problem has been fixed in 4.13.0

**Comment by AlexanderKgr** [comment]
I am still facing this.
I am using cloudstack 4.14 with xcp-ng 8.1
I have an instance of ubuntu server 18.04. Take snapshot without memory and revert it, i have a message that fails
looking at logs i have

2020-09-30 08:59:57,139 ERROR [o.a.c.s.v.DefaultVMSnapshotStrategy] (Work-Job-Executor-82:ctx-877a4923 job-2981/job-2982 ctx-ffa7b074) (logid:c780de19) Creating VM snapshot: i-2-233-VM_VS_20200930055955 failed due to com.cloud.utils.exception.CloudRuntimeException:  Hypervisor com.cloud.hypervisor.xenserver.resource.XenServer650Resource doesn't support guest OS type Ubuntu 18.04 LTS. you can choose 'Other install media' to run it as HVM
com.cloud.utils.exception.CloudRuntimeException: Creating VM snapshot: i-2-233-VM_VS_20200930055955 failed due to com.cloud.utils.exception.CloudRuntimeException:  Hypervisor com.cloud.hypervisor.xenserver.resource.XenServer650Resource doesn't support guest OS type Ubuntu 18.04 LTS. you can choose 'Other install media' to run it as HVM

**Comment by miesiu** [comment]
Issue exist on cloudstack 4.16.1 with xcp-ng 8.2

**Comment by matheusfontes** [comment]
Neither take snapshot nor revert snapshot works on cloustack 4.16.1 with xcp-ng 8.2
