### ISSUE TITLE
Remove 'make redundant' option from the restart network pop-up.

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4052]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI and Primate
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### SUMMARY

This should be defined at an offering level, simply having the option to turn a network into redundant shouldn't be available on restart as it's confusing people 

##### STEPS TO REPRODUCE

~~~
Restart a network and observe the option
~~~

![Screenshot 2020-04-30 at 14 41 05](https://user-images.githubusercontent.com/13551960/80718872-5f677580-8b03-11ea-8257-268fe2d72fa9.png)

**Comment by andrijapanicsb** [comment]
@borisstoyanov did you report this to the Primate project (raised bug there?)

**Comment by borisstoyanov** [comment]
No, I've marked the component as UI and Primate, it needs to be tested against both when picket up.

**Comment by rhtyd** [comment]
@borisstoyanov this is fixed in Primate
![Screenshot from 2020-07-08 11-42-01](https://user-images.githubusercontent.com/95203/86883710-11c54580-c110-11ea-9fb4-2d0cffc84189.png)

**Comment by borisstoyanov** [comment]
with latests master installed from nightly I can still see this
![Screenshot 2020-11-11 at 13 09 39](https://user-images.githubusercontent.com/13551960/98804728-36fbf480-241f-11eb-9230-738f836ff97e.png)

**Comment by borisstoyanov** [comment]
this is cloudstack-primate-1.0.0-20201110.x86_64.rpm

**Comment by weizhouapache** [comment]
@rhtyd @borisstoyanov 
I think this works fine in old UI, why remove it from Primate ?

**Comment by borisstoyanov** [comment]
@weizhouapache while it is working good in majority of cases, this is something that should be set on a service offering level, it's simply not in the right place.

**Comment by weizhouapache** [comment]
@borisstoyanov  what you said is an option to change a network to redundant.

makeredundant is an optional parameter of restartnetwork. it would be better to support it on Primate UI.

```
(local) mgt01 > restart network
cleanup=        filter=         id=             makeredundant=
```

**Comment by borisstoyanov** [comment]
yes @weizhouapache, what I mean is not just the UI but this API shouldn't be there at all. Cloudstack uses offering model to set limits on the resources it gives to users. So if a user wants to have a redundant VR he should have such offering, simply changing that with a VR restart is in conflict with this model.

**Comment by borisstoyanov** [comment]
![Screenshot 2020-11-12 at 10 44 55](https://user-images.githubusercontent.com/13551960/98916674-1cd01e00-24d4-11eb-8a1d-c1b3471504ec.png)
As you see this seems to be available to users as well which is not really great.

**Comment by weizhouapache** [comment]
> ![Screenshot 2020-11-12 at 10 44 55](https://user-images.githubusercontent.com/13551960/98916674-1cd01e00-24d4-11eb-8a1d-c1b3471504ec.png)
> As you see this seems to be available to users as well which is not really great.

yeah. however we have used that feature for years.
so if you want to change it, could you add a global setting to enable/disable the feature to keep backwards compatibility ?

**Comment by borisstoyanov** [comment]
We've discussed previously that we'll simply remove it from UI for now as first step, but it's still going to be there in cmk. Does this work for you @weizhouapache ?

**Comment by weizhouapache** [comment]
@borisstoyanov thanks for your explanation. could you give me a link about the discussion ? thanks !

**Comment by borisstoyanov** [comment]
it's just this issue, not sure if there's anything in the primate repo.

**Comment by rhtyd** [comment]
This was a recently added UI feature, available via API though. We can hide it in UI as users from 4.9/4.11/4.13 can cause additional/unanticipated VR resource consumption for IaaS hosting/providers.
