### ISSUE TITLE
Multiple Public Subnets Single Shared Network ( Metadata Error )

### ISSUE THREAD

**Issue by benmcguire79** [apache/cloudstack#4931]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

Advanced Networking with SG
One defaultGuestNetwork ( 2 x subnets setup using legacy interface.
Example:   188.165.185.64/28     51.255.101.128/26

The first subnet /28 was added when the guestnetwork was created. We can manually add an IP from the /26 subnet ( using the legacy interface and DHCP is working and IP is assigned to the instance. When querying the metadata server for the password the instance seeks out the /28 VR gateway which fails.

##### SUMMARY
Creating more than one public CIDR in the DefaultGuestNetwork fails to obtain password from cloud-init metadata server.

##### STEPS TO REPRODUCE

~~~
2021-04-16 13:29:47,489 - DataSourceCloudStack.py[DEBUG]: Crawl of metadata service took 0 seconds
2021-04-16 13:29:47,489 - util.py[DEBUG]: Running command ['wget', '--quiet', '--tries', '3', '--timeout', '20', '--output-document', '-', '--header', 'DomU_Request: send_my_password', ' xxx.xxx.xxx..100:8080'] with allowed return codes [0] (shell=False, capture=True)
2021-04-16 13:30:51,568 - util.py[WARNING]: Failed to fetch password from virtual router 188.165.185.100
2021-04-16 13:30:51,570 - util.py[DEBUG]: Failed to fetch password from virtual router  188.165.185.100
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceCloudStack.py", line 131, in _get_data
    set_password = password_client.get_password()
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceCloudStack.py", line 58, in get_password
    password = self._do_request('send_my_password')
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceCloudStack.py", line 53, in _do_request
    '{0}:8080'.format(self.virtual_router_address)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2084, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['wget', '--quiet', '--tries', '3', '--timeout', '20', '--output-document', '-', '--header', 'DomU_Request: send_my_password', ' xxx.xxx.xxx.:8080']
Exit code: 4




1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 1e:00:52:01:02:43 brd ff:ff:ff:ff:ff:ff
    inet 188.165.185.100/27 brd 188.165.185.127 scope global eth0
       valid_lft forever preferred_lft forever
    inet 51.255.101.129/26 brd 51.255.101.191 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0e:00:a9:fe:7f:ef brd ff:ff:ff:ff:ff:ff
    inet 169.254.127.239/16 brd 169.254.255.255 scope global eth1
       valid_lft forever preferred_lft forever
~~~

##### EXPECTED RESULTS

- Obtain password from VR
- instance should query correct gateway of VR for the additional subnet.
~~~

~~~

##### ACTUAL RESULTS
- Failed to fetch password from virtual router  188.165.185.100 |  
-- | --

- Instance is using gateway from the subnet that was originally created when the defaultnetwork was setup.
Get request to the VR using both IP  and DNS name is working as per below. Curl request inside the instance works. When booting a Ubuntu or CentOS instance cloud-init times out when accessing the server_password. 
~~~

curl http://data-server./latest/meta-data/local-hostname
Test51[root@test51 cloud.cfg.d]# 

~~~

**Comment by DaanHoogland** [comment]
can you add 'real' rfc1918 examples? from this we can not really see where you wnet wrong, @benmcguire79. I'm not saying you are wrong. I've seen a similar issue recently and it might even duplicate that one. .

**Comment by benmcguire79** [comment]
Hi Dan

I have updated the initial report with the actual IPs. In addition here is the full cloud-init.log from the test VM. As stated, ssh keys with but password does not.


https://mega.nz/file/ArwlTY7Q#I0a7C30mXhf7YfSpAjG3IwmXX8VtRAfEN5LVzRcwPCk
Also here are the screenshots if they help.

![Screenshot 2021-04-19 at 10 43 43](https://user-images.githubusercontent.com/19871799/115217665-a4fac500-a0fd-11eb-9cfe-80b7a7618022.png)
![Screenshot 2021-04-16 at 12 22 42](https://user-images.githubusercontent.com/19871799/115217680-a7f5b580-a0fd-11eb-9855-8925df0c64c4.png)

**Comment by benmcguire79** [comment]
from the screenshots above it appears the CentOS7 vm is trying to use the first address of the subnet ( 51.255.101.131 ) which Im unsure why it chooses that 131 address and not 129 which is the first usable IP in the subnet.

BUT, the cloudinit log says it is trying to use the 188.165.185.100 which is the VR. Im assuming it is becuase of the DNS entry in the VR for data-server. 

Read from http://188.165.185.100/latest/meta-data/availability-zone (200, 6b) after 1 attempts
2021-04-19 09:43:09,840 - url_helper.py[DEBUG]: [0/6] open 'http://188.165.185.100/latest/meta-data/instance-id' with {'url': 'http://188.165.185.100/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/19.4'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration

Let me know if I can provide further information.

**Comment by benmcguire79** [comment]
Just tested with Ubuntu 16.04 and it tries 51.255.101.129 which still fails.Unsure why the first one ( CentOS 7 ) uses 51.255.101.131 and Ubuntu tries 51.255.101.129 ???

![Screenshot 2021-04-19 at 11 14 29](https://user-images.githubusercontent.com/19871799/115220466-7af6d200-a100-11eb-93a9-f818c6c6669f.png)

**Comment by benmcguire79** [comment]
HI.

Is there any update on this. It would be great to get this fix included in the 4.15.1 release as it is now impossible to use multiple subnets in a shared network and have the password server working.

**Comment by rhtyd** [comment]
I'm tentatively assigning the 4.15.1.0 milestone (doesn't guarantee a fix will make into the release) for investigation.
cc @wido @GabrielBrascher @weizhouapache have you seen something in your SG-based environments?

**Comment by wido** [comment]
> I'm tentatively assigning the 4.15.1.0 milestone (doesn't guarantee a fix will make into the release) for investigation.
> cc @wido @GabrielBrascher @weizhouapache have you seen something in your SG-based environments?

We have a strict one-subnet-per-network policy on our advanced zones. Each VXLAN network has one IPv4 and one IPv6 subnet.

In the past we have seen too many issues with multiple subnets per network and therefor we chose to not implement this anymore.

**Comment by benmcguire79** [comment]
> I'm tentatively assigning the 4.15.1.0 milestone (doesn't guarantee a fix will make into the release) for investigation.
> cc @wido @GabrielBrascher @weizhouapache have you seen something in your SG-based environments?

Thank you @rhtyd @wido I guess we will await 4.15.1.0 and see if any changes inthat makes any difference. Should the issue still persist I guess we will go with @wido and use one subnet per network....a pain but if there's no other way :)  I was thinking it maybe a simialr issue to https://github.com/apache/cloudstack/issues/4865

**Comment by weizhouapache** [comment]
> > I'm tentatively assigning the 4.15.1.0 milestone (doesn't guarantee a fix will make into the release) for investigation.
> > cc @wido @GabrielBrascher @weizhouapache have you seen something in your SG-based environments?
> 
> We have a strict one-subnet-per-network policy on our advanced zones. Each VXLAN network has one IPv4 and one IPv6 subnet.
> 
> In the past we have seen too many issues with multiple subnets per network and therefor we chose to not implement this anymore.

@rhtyd @wido 
We have multiple subnets many years ago (cloudstack 2.2.14 ?), when we upgraded to a major version, we created separated shared network for each subnet. for now each shared network have only 1 subnet on our productions (same as pcextreme).

**Comment by rhtyd** [comment]
Thanks @weizhouapache @wido. @benmcguire79 can you help test the latest 4.15.1 and report your findings, or are you happy to accept the general prod use-case (i.e. use single subnet per network) and close the issue?

**Comment by benmcguire79** [comment]
Hi @rhtyd . I am happy to test 4.15.1 once it is released as Im patiently waiting for it.  For our use case setting up multiple networks for each subnet is not ideal as we have 20+ subnets and having 20+ networks again is not ideal. I see someone else raised the same issue ( albeit with vmware ) but from what I read it is the same issue ( https://github.com/apache/cloudstack/issues/4943 ) with the data-server and hosts file. In any event as soon as 4.15.1 is released ill immediately test and advise you of my findings. FYI i have tested with an isolated network with multiple internal subnets and these work with no issues....it appears only muliple public subnets on a single network is causing the issue.

**Comment by rhtyd** [comment]
cc @DaanHoogland

**Comment by DaanHoogland** [comment]
@wei @wido @rhtyd @benmcguire79 I'll create a doc pr to describe the way of working mentioned and do a short test to confirm @benmcguire79 's limitation.

**Comment by DaanHoogland** [comment]
@benmcguire79 this is actually already covoured in the docs. From http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking/security_groups.html?highlight=security%20groups#limitations

```
Two IP ranges with the same VLAN and different gateway or netmask in security group-enabled shared network.
```

Do you agree this is your use-case? (if so, can you close the issue?)

**Comment by benmcguire79** [comment]
> @benmcguire79 this is actually already covoured in the docs. From http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking/security_groups.html?highlight=security%20groups#limitations
> 
> ```
> Two IP ranges with the same VLAN and different gateway or netmask in security group-enabled shared network.
> ```
> 
> Do you agree this is your use-case? (if so, can you close the issue?)

Hi @DaanHoogland 

Yes agreed. Probably move to NAT moving forward. Thank you for the input.

**Comment by weizhouapache** [comment]
fixed by #5013

**Comment by ccycv** [comment]
I still have the same issue, even in 4.15.2, it will not work with basic network ( or advanced with guest  ) with multiple subnets.  

This issue is persistent to the VMs with cloud-init:

Ubuntu 16 - OK
Ubuntu 18 - OK
Ubuntu 20 - OK
CentOS7 - Not working 
CentOS8 - Not working 
Debian8 -  Not working 
Debian9   - OK
Debian10 - OK

It is simple to reproduce, add multiple CIDR to the same guest router, deploy multiple instances, when a new VM is going to be deployed under different subnet, for some reasons the returned data-server IP is not from VM subnet, it is the IP which is defined in /etc/hosts into the router, example;
149.xx.xx.99 r-xxx-VM data-server  

And because it is from different subnet, there is no password saved in the file for different subnet (in router ). in this case, no password is going to be set for this VM.

If I execute this:  "cat /var/lib/dhclient/dhclient--eth0.lease | grep dhcp-server-identifier" into the VM the returned IP is the right one. Even if I try to add this to VM host file( IP data-server) ,it is not working, the cloud-init it is using the IP for metadata, and not the host "http://data-server".

Tested with :
4.15.0 + VMware
4.15.1 + VMware
4.15.2 + VMware

At this point, I'm not sure if this is a cloud-init issue or cloudstack.

**Comment by weizhouapache** [comment]
> I still have the same issue, even in 4.15.2, it will not work with basic network ( or advanced with guest ) with multiple subnets.
> 
> This issue is persistent to the VMs with cloud-init:
> 
> Ubuntu 16 - OK
> Ubuntu 18 - OK
> Ubuntu 20 - OK
> CentOS7 - Not working
> CentOS8 - Not working
> Debian8 - Not working
> Debian9 - OK
> Debian10 - OK
> 
> It is simple to reproduce, add multiple CIDR to the same guest router, deploy multiple instances, when a new VM is going to be deployed under different subnet, for some reasons the returned data-server IP is not from VM subnet, it is the IP which is defined in /etc/hosts into the router, example;
> 149.xx.xx.99 r-xxx-VM data-server
> 
> And because it is from different subnet, there is no password saved in the file for different subnet (in router ). in this case, no password is going to be set for this VM.
> 
> If I execute this: "cat /var/lib/dhclient/dhclient--eth0.lease | grep dhcp-server-identifier" into the VM the returned IP is the right one. Even if I try to add this to VM host file( IP data-server) ,it is not working, the cloud-init it is using the IP for metadata, and not the host "http://data-server".
> 
> Tested with :
> 4.15.0 + VMware
> 4.15.1 + VMware
> 4.15.2 + VMware
> 
> At this point, I'm not sure if this is a cloud-init issue or cloudstack.

@ccycv it seems to be a bug in cloudstack. can you create file an issue ?
