### ISSUE TITLE
UI: rbd volume snapshot cannot be rolledback

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5161]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
4.15.1.0
~~~

##### OS / ENVIRONMENT

CloudStack 4.15.0.0
ceph 15.2.11
ubuntu 20.04
##### SUMMARY

Unable to roll back RBD VOLUME snapshot on UI
Use API to complete rbd volume snapshot rollback

snapshot.backup.to.secondary=false
kvm.snapshot.enabled=true

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@div8cn have you tested this on 4.15.1.0 RC2? cc @GabrielBrascher @wido

**Comment by div8cn** [comment]
4.15.1 RC3 also has this problem

**Comment by GabrielBrascher** [comment]
@div8cn by unable you mean that there is not a "button" on the new UI for this?
Or do you mean a failure on the revert via the UI?

**Comment by div8cn** [comment]
no rollback button

**Comment by GabrielBrascher** [comment]
@div8cn thanks for confirming.

@rhtyd I am having the same issue; the UI button for reverting a snapshot is "missing".

The new UI presents the button only if the snapshot response has `revertable` as `true`. However, I am getting `revertable` as `false` in snapshots. This includes also a snapshot taken on NFS, not just Ceph/RBD.

List Snapshots via API.
```
cmk> list snapshots filter=name,state,revertable
+-------------------+----------+------------+
|       NAME        |  STATE   | REVERTABLE |
+-------------------+----------+------------+
| primary-nfs-snap2 | BackedUp | false      |
| primary-nfs-snap  | BackedUp | false      |
| test-snap1-rbd    | BackedUp | false      |
+-------------------+----------+------------+
```

Mysql select on snapshot_store_ref checking that it indeed happens with snapshots taken on `NFS` & `RBD`.

```
> select store_role,install_path,state from snapshot_store_ref order by id desc limit 3;
+------------+---------------------------+-------+
| store_role | install_path              | state |
+------------+---------------------------+-------+
| Primary    | /mnt/<uuid>/<uuid>/<uuid> | Ready |
| Primary    | /mnt/<uuid>/<uuid>/<uuid> | Ready |
| Primary    | rbd/<uuid>/<uuid>         | Ready |
+------------+---------------------------+-------+
```

The UI then will not present the revertable button.

1. Example of the UI buttons for the tested snapshots:
![image](https://user-images.githubusercontent.com/5025148/123819017-d4813700-d8cf-11eb-98fc-a77ab63224b0.png)


2. Example with the UI "ignoring" the revertable in the response:
![image](https://user-images.githubusercontent.com/5025148/123818857-b74c6880-d8cf-11eb-9a7a-fb061ae02dfa.png)

**Comment by nvazquez** [comment]
@GabrielBrascher could you work on this issue?

**Comment by rhtyd** [comment]
@utchoang can you check if we show the revert button in UI for snapshots, if there's any check for rbd/ceph/kvm?

**Comment by utchoang** [comment]
@rhtyd @GabrielBrascher  In new UI, revert button is only visible when `state === 'BackedUp' && revertable === true`. So in this case, when will the revert button be displayed?

**Comment by rhtyd** [comment]
Thanks for sharing @utchoang as per @GabrielBrascher 's comment looks like we need to check the 'revertable' setting - can you confirm against the legacy UI from 4.15/4.14 and raise a PR.
@GabrielBrascher @div8cn any comments? Are you for example seeing the option in old UI?

**Comment by GabrielBrascher** [comment]
From what I have been debugging it is related to the Snapshot response not placing the snapshots in RBD as revertable.
I will take a deeper look at this but it does not look like a UI issue but instead an API response issue.

**Comment by utchoang** [comment]
@rhtyd Through research in branch 4.14, the new UI revert button display condition is the same. I think the problem here is from the API?
https://github.com/apache/cloudstack/blob/4.14/ui/scripts/storage.js#L3199

**Comment by GabrielBrascher** [comment]
@utchoang @div8cn @nvazquez @rhtyd I've done some tests with one of the recent commits in the main and it looks to be working fine to revert RBD/Ceph snapshots with KVM.

The button is displayed in the UI and the CephStrategy is called as expected.

**Comment by nvazquez** [comment]
Thanks @GabrielBrascher, does it need backporting to the 4.15 branch?

**Comment by rhtyd** [comment]
Ping @GabrielBrascher @utchoang any update?

**Comment by utchoang** [comment]
@rhtyd cc @GabrielBrascher I don't know how to solve this, because in my opinion, compared to the old UI, it still seems to work properly.

**Comment by rhtyd** [comment]
@GabrielBrascher can you advise if this is something fixed in main but not 4.15 branch, or is this not valid anymore - can we close this issue?

**Comment by rhtyd** [comment]
cc @davidjumani

**Comment by GabrielBrascher** [comment]
@nvazquez @rhtyd I was not able to detect any change or recently merged PR that would affect RBD rollback on UI nor on API. Still not sure why my tests differ now than the older tests.

**Comment by rhtyd** [comment]
@GabrielBrascher can you just confirm if you tested main or 4.15 branch?

**Comment by rhtyd** [comment]
@utchoang @shwstppr can you check if the revert snapshot button is shown with same logic in main as in 4.15 and follows the same logic as old UI?

**Comment by rhtyd** [comment]
I see same logic on main as in 4.15, https://github.com/apache/cloudstack/blob/4.15/ui/src/config/section/storage.js#L306
I'm moving this to 4.16 to be tested and closed. cc @nvazquez

**Comment by rhtyd** [comment]
@GabrielBrascher can you confirm and close this if it's no longer an issue for main/4.16?

**Comment by rhtyd** [comment]
@GabrielBrascher @utchoang @svenvogel @nvazquez @sureshanaparti @davidjumani @shwstppr @Pearl1594 @DaanHoogland @weizhouapache - any update on this, who's assigned/working on this? Thanks.

**Comment by utchoang** [comment]
Same logic revert button from main and 4.15 branch. I don't think this issue from UI. @GabrielBrascher Can you confirm where this error is coming from?

**Comment by nvazquez** [comment]
Closing this issue as per @GabrielBrascher's comment https://github.com/apache/cloudstack/issues/5161#issuecomment-902256567 after testing on main branch
