### ISSUE TITLE
upgrade xerces to 2.12.2 due to cve

### ISSUE THREAD

**Issue by pjfanning** [apache/cloudstack#5943]
##### ISSUE TYPE

 * Bug Report

https://mvnrepository.com/artifact/xerces/xercesImpl -- recent cve

**Comment by sureshanaparti** [comment]
Fixed in #5944

**Comment by pjfanning** [comment]
linked https://github.com/apache/cloudstack/pull/5968 too (still an issue with the xerces upgrade)
