### ISSUE TITLE
CloudStack DB upgrade failure causes upgrade mess

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6608]
If CloudStack is being upgraded and a DB issue is hit (say table is already altered, forgot to have systemvmtemplate in the deb/rpm build etc), then the whole transaction isn't reverted maybe partially. This causes changes to persist, changes such as new tables being added, existing tables/views altered. As an operator, I would prefer CloudStack to revert its DB changes when an DB upgrade path issue is hit.

##### ISSUE TYPE

 * Bug Report
 * 
##### COMPONENT NAME

~~~
DB, Upgrades
~~~

**Comment by DaanHoogland** [comment]
related to #6980 . maybe possible to combine the two

**Comment by rohityadavcloud** [comment]
Was this resolved now cc @weizhouapache if you know?

**Comment by weizhouapache** [comment]
> Was this resolved now cc @weizhouapache if you know?

@rohityadavcloud 
AFAIK no, acs still do not have rollback mechanism if upgrade fails

**Comment by rohityadavcloud** [comment]
Closing on Wei's remarks. Let's fix it, revisit in future.
